EOS- 27644 Test and qualify granular deployment - Data Pod
zahidsk/cortx-k8s pull request #1
Opened 2022-02-03 18:24 UTC by zahidsk

2022-02-04 03:29 UTC, ujjwalpl requested changes

2022-02-04 03:29 UTC, ujjwalpl commented on k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-configmap/templates/cluster-template.yaml
> -  - name: server_node
You dont have to modify existing template and delete things from there. Full deployment will not work. 
Create new templates for data only

2022-02-04 03:29 UTC, ujjwalpl commented on k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-configmap/templates/config-template.yaml
> -  s3:
You dont have to modify existing template and delete things from there. Full deployment will not work.
Create new templates for data only

2022-02-04 03:29 UTC, ujjwalpl commented on k8_cortx_cloud/deploy-cortx-cloud.sh
> +        # # Generate cluster server node file with type server_node in "node-info" folder
Why is this code commented?

2022-02-04 03:29 UTC, ujjwalpl commented on k8_cortx_cloud/deploy-cortx-cloud.sh
> +# deployCortxControl
Code should support both full or data only deployment. Not just data only.

2022-02-04 06:26 UTC, ujjwalpl requested changes

2022-02-07 07:24 UTC, closed without merging

2022-02-07 07:25 UTC, zahidsk commented
Raising new PR with new template files created for Data pod